# Generated by Django 4.1.5 on 2023-01-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
