# Generated by Django 4.1.5 on 2023-03-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_orders_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(default='', max_length=50),
        ),
    ]
