# Generated by Django 4.1.5 on 2023-03-16 14:04

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_orders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=phone_field.models.PhoneField(default=0, max_length=31),
        ),
    ]
