# Generated by Django 4.1.5 on 2023-03-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='phone',
            new_name='phone_no',
        ),
    ]
