# Generated by Django 4.1.5 on 2023-03-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_rename_phone_orders_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone_no',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
