# Generated by Django 4.1.5 on 2023-03-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_orders_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
